app_url            = "http://localhost"

[nginx]
worker_rlimit_nofile = 8192
worker_processes     = "auto"
worker_connections = 8000

[http]
listen_port        = 80
sendfile          = "on"
tcp_nopush        = "on"
tcp_nodelay       = "on"
keepalive_timeout = "20s"
